### ISSUE TITLE
ImportError: cannot import name local_zone

### ISSUE THREAD

**Issue by RickCogley** [tbabej/task.default-date-time#7]
Hi - thank you for your work on this script and taskwarrior in general. I've installed this hook script in taskwarrior, and also taskpirate as specified. I'm getting the following error about tasklib not being able to import "local_zone". How could I troubleshoot this? I'm using Mac OS X 10.11.4 and brew-installed Python 2.7 and 3.5. 

The below is the trace I'm seeing. 

Kind regards,
Rick 

```
┌─( ~ )────────────────────────────────────────────────────────────────────────────────────( TW Done:1 Due:9 Overdue:18 Next:63 @jrcmbp2015 )─┐
└─❱❱❱ task 291 ann do it today                                                                                                  +7990 10:56 ❰─┘
Traceback (most recent call last):
  File "/Users/rcogley/.task/hooks/on-modify-pirate", line 40, in <module>
    for hook in find_hooks('pirate_mod'):
  File "/Users/rcogley/.task/hooks/on-modify-pirate", line 25, in find_hooks
    module = imp.load_source(module_name, module_path)
  File "/Users/rcogley/.task/hooks/default-date-time/pirate_mod_default_time.py", line 3, in <module>
    from tasklib.task import Task, local_zone
ImportError: cannot import name local_zone
Hook Error: Expected feedback from a failing hook script.

┌─( ~ )────────────────────────────────────────────────────────────────────────────────────( TW Done:1 Due:9 Overdue:18 Next:63 @jrcmbp2015 )─┐
└─❱❱❱ pip2 install tzlocal                                                                                                 4 ⏎  +7991 11:01 ❰─┘
Requirement already satisfied (use --upgrade to upgrade): tzlocal in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/site-packages (from tzlocal)
```

**Comment by RickCogley** [comment]
My current timezone is Japan time if that makes any difference: 

```
sudo systemsetup -gettimezone
Time Zone: Asia/Tokyo
```

**Comment by tbabej** [comment]
Hi,
can you please check you have the latest tasklib installed? The 1.0.0 version is available via pip (older versions should work too, but probably not that much into past).

As far as the troubleshooting goes, just run your regular python shell, and try to import the objects in question:

```
$ python
>>> from tasklib.task import Task, local_zone
>>>.
```

**Comment by RickCogley** [comment]
Hi @tbabej, thanks for your help. Here are the results: 

```
pip show tasklib                                                                                                     1 ⏎  +8005 20:29 ❰─┘
---
Metadata-Version: 2.0
Name: tasklib
Version: 1.0.0
Summary: Python Task Warrior library
Home-page: https://github.com/robgolding63/tasklib
Author: Rob Golding
Author-email: rob@robgolding.com
Installer: pip
License: BSD
Location: /usr/local/lib/python3.5/site-packages
Requires: six, pytz, tzlocal
Classifiers:
  Development Status :: 4 - Beta
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  License :: OSI Approved :: BSD License
  Topic :: Software Development :: Libraries :: Python Modules
  Intended Audience :: Developers
```

And...

```
python                                                                                                               1 ⏎  +8007 20:30 ❰─┘
Python 2.7.11 (default, Apr 20 2016, 08:25:44)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tasklib.task import Task, local_zone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name local_zone
```

I'm afraid I don't know python or where to look after this, so, I hope you'll kindly give me a point in the right direction. 

Sincerely
Rick

**Comment by RickCogley** [comment]
Also "pip2 show tasklib" shows it's v 1.0.0 under 2.7.

**Comment by tbabej** [comment]
Okay, I think I figured it out. I actually had one (unpushed) patch on my branch since September 2015, which fixes the issue. Please update the repo, it should work fine now.

**Comment by RickCogley** [comment]
@tbabej thanks very much; that was it!
Confirm it's fixed. Thanks again for your work. Having the default due time set to something more reasonable is very helpful to me.
