### ISSUE TITLE
ValueError: Timezone offset does not match system offset: 0 != 3600

### ISSUE THREAD

**Issue by lucytallents** [tbabej/task.default-date-time#9]
HI, I just tried installing this on top of taskpirate and tasklib (all new to me today).  I edited the script to my preferred default time (17,0,0) but new tasks still have a due time of midnight.  I tried running *pirate_add_default_time.py* and *pirate_mod_default_time.py in the terminal* (is this necessary?) but got the following error message for both:
ValueError: Timezone offset does not match system offset: 0 != 3600. Please, check your config files.

Here's the full trace, plus info on my packages:
python pirate_mod_default_time.py 
Traceback (most recent call last):
  File "pirate_mod_default_time.py", line 4, in <module>
    from tasklib import Task, local_zone
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/__init__.py", line 1, in <module>
    from .backends import TaskWarrior
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/backends.py", line 11, in <module>
    from .task import Task, TaskQuerySet, ReadOnlyDictView
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/task.py", line 10, in <module>
    from .serializing import SerializingObject
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/serializing.py", line 12, in <module>
    local_zone = tzlocal.get_localzone()
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != 3600. Please, check your config files.
 
python pirate_add_default_time.py 
Traceback (most recent call last):
  File "pirate_add_default_time.py", line 4, in <module>
    from tasklib import Task, local_zone
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/__init__.py", line 1, in <module>
    from .backends import TaskWarrior
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/backends.py", line 11, in <module>
    from .task import Task, TaskQuerySet, ReadOnlyDictView
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/task.py", line 10, in <module>
    from .serializing import SerializingObject
  File "/home/lucy/.local/lib/python3.6/site-packages/tasklib/serializing.py", line 12, in <module>
    local_zone = tzlocal.get_localzone()
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/home/lucy/.local/lib/python3.6/site-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != 3600. Please, check your config files.

pip show tasklib
Name: tasklib
Version: 1.2.1
Summary: Python Task Warrior library
Home-page: https://github.com/robgolding63/tasklib
Author: Rob Golding
Author-email: rob@robgolding.com
License: BSD
Location: /home/lucy/.local/lib/python3.6/site-packages
Requires: six, pytz, tzlocal
Required-by: 

My system timezone is GMT, set automatically.

What other packages should I check/update?  Have I misunderstood how to get this working?

Thanks for any help - really appreciate your effort both in creating these packages and any replies!

**Comment by tbabej** [comment]
This seems to be coming from tzlocal, maybe this issue is relevant: https://github.com/regebro/tzlocal/issues/73
